# -*- coding: utf-8 -*-

class DkuModelAccessorConstants(object):
    MODEL_ID = 'model_id'
    VERSION_ID = 'version_id'
    REGRRSSION_TYPE = 'REGRESSION'
    DKU_MULTICLASS_CLASSIF = 'MULTICLASS'
    DKU_BINARY_CLASSIF = 'BINARY_CLASSIFICATION'
    CLASSIFICATION_TYPE = 'CLASSIFICATION'
    CLUSTERING_TYPE = 'CLUSTERING'
    MAX_NUM_ROW = 1000000
    CUMULATIVE_PERCENTAGE_THRESHOLD = 90
    SURROGATE_TARGET = "_dku_predicted_label_"
    FEAT_IMP_CUMULATIVE_PERCENTAGE_THRESHOLD = 95
    CUMULATIVE_IMPORTANCE = 'cumulative_importance'
    FEATURE = 'feature'
    IMPORTANCE = 'importance'
    RANK = 'rank'
    CLASS = 'class'
    PERCENTAGE = 'percentage'
    DKU_XGBOOST_CLASSIF = 'XGBOOST_CLASSIFICATION'
    DKU_XGBOOST_REGRESSION = 'XGBOOST_REGRESSION'
